-- Full seed – 19 crew members – all normalized, The789 + dogecoin chain
-- Run this AFTER the table is created

INSERT INTO crew_members (
  id, name, pfp, bio, role, tier, status, verified, is_active_host, activity_score,
  space_title, space_description, space_time_utc, space_platform, space_recurring,
  x, youtube, twitch, kick, tiktok, instagram, discord, telegram, github,
  daos, groups, tags, custom_badges, wallets, blockchain, created_at
) VALUES
  ('anthemhayek', 'Anthem', '/crew/Anthem.webp', 'Veteran fintech pioneer and gold-backed crypto innovator. Co-founder of AnthemGold (HayekGold tokens) and Anthem Vault. Drops weekly curated insights on decentralized money, Bitcoin, and navigating chaos in crypto. Weathering markets with killer tunes and zero-BS clarity.', 'Blockchain Pioneer', 'fam', 'active', true, true, 0, 'WEATHER THE CRYPTO', 'Crypto news, market moves, and killer tunes.', '20:00-21:00', 'x', true, 'anthemhayek', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY[], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('armormetax', 'Armor', '/crew/Armor.webp', 'Biggest 789 ride-or-die. Shows up when the timeline gets ugly, blocks the FUD, rallies the fam, and holds the line harder than anyone. Vibes’ counterpart in the trenches. Pure loyalty. Zero quit.', 'Redpill Gunslinger', 'core', 'active', true, false, 0, '', '', '', '', false, 'armormetax', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY['inner-circle','defense-cabal'], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('artsymeta', 'Artsy', '/crew/Artsy.webp', 'Underground art dealer. Showcases raw crypto pixels and meta rebellion. Turns late-night degens into cultured wolves.', 'Pixel Savage', 'fam', 'active', false, true, 0, 'WOOF OF ART STREET', 'Raw crypto art, pixels & meta rebellion.', '07:00-08:00', 'x', true, 'artsymeta', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY['pixel-cabal'], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('barkmeta', 'Bark', '/crew/Bark.webp', 'Doginal Dogs co-founder and relentless Web3 voice. Daily host, brand builder, community architect. Turned underdog energy into #1 NFT ecosystem on Dogecoin. Builds together, stays disciplined, leads with action. This dog hunts.', 'Timeline Warlord', 'inner', 'active', true, true, 0, 'STATE OF CRYPTO', 'The #1 space on Earth for brand development.', '22:00-00:00', 'x', true, 'barkmeta', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY['doginal-dogs','bark-media'], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('crypto_sauce', 'Sauce', '/crew/Sauce.webp', 'Late-night sauce chef. Serves hot news, market alpha, and community spice after sunset.', 'Crypto Chef', 'fam', 'active', false, true, 0, 'CRYPTO SAUCE', 'Late-night news, market alpha & community spice.', '03:00-04:00', 'x', true, 'crypto_sauce', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY[], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('dreammetax', 'Dream', '/crew/Dream.webp', 'Midnight mystic. Drops spiritual alpha and links souls across chains. Turns late-night scrolls into profound connections.', 'Canine Prophet', 'fam', 'active', false, true, 0, 'THE DREAM SPACE', 'Dimensional guidance & cross-chain soul links.', '04:00-05:30', 'x', true, 'dreammetax', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY[], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('gatormetax', 'Gator', '/crew/Gator.webp', 'Swamp growth monster. Teaches timeline hygiene and engagement hacks. Turns weak accounts into predators.', 'The Nine', 'core', 'legend', true, true, 0, 'THE SWAMP', 'X account health, growth & engagement hacks.', '02:00-03:00', 'x', true, 'gatormetax', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY['raid-team'], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('godsburnt', 'Shibo', '/crew/Shibo.webp', 'Alpha Hunter King. Runs the loudest crypto show on the planet. Spills hidden gems, market nukes, and savage takes that move charts. Pure degen adrenaline.', 'Alpha Hunter King', 'fam', 'legend', true, true, 0, 'THE CRYPTO SHOW', '#1 space on Earth for crypto news & alpha.', '15:00-17:00', 'x', true, 'godsburnt', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY['alpha-crew','founder'], ARRAY['morning-raid','alpha-caller'], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('gramixmeta', 'Grami', '/crew/Grami.webp', 'Dawn patrol degen philosopher. Drops ancient redpills and raw mindset alpha while normies sleep. Turns coffee into enlightenment and weak hands into diamond paws.', 'Loyalty Enforcer', 'fam', 'active', false, true, 0, 'DOGINAL DOGS RADIO', 'Knowledge, wisdom, mindset redpills & personal development.', '11:00-12:00', 'x', true, 'gramixmeta', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY[], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('growxmeta', 'Grow', '/crew/Grow.webp', 'Graveyard shift growth guru. Combines mindset upgrades with brand warfare while everyone sleeps.', 'Squad General', 'fam', 'active', false, true, 0, 'GROW SHOWS CRYPTO', 'Personal growth meets brand warfare.', '05:00-06:00', 'x', true, 'growxmeta', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY['mindset-cabal'], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('jeepmeta', 'Jeep', '/crew/Jeep.webp', 'The Dev warlord. Builds the yellow empire, ships savage code, and keeps the crew stacked. Turns bugs into features and degens into builders.', 'Dev Sovereign', 'core', 'legend', true, false, 67, '', '', '', '', false, 'jeepmeta', '', '', '', '', '', '', '', 'jeepmeta', ARRAY['The789'], ARRAY['inner-circle','code-snipers'], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('leahbluewater', 'Leah', '/crew/Leah.webp', 'Queen of the morning raid. Hits degens with fresh crypto news, chain drama, and zero-bullshit intel before wake-up time. Keeps the pack informed and ready to ape.', 'The Queen of Crypto', 'fam', 'active', true, true, 0, 'THE KICKOFF', 'Fresh blockchain news, chain drama & zero-BS intel.', '11:00-12:00', 'x', true, 'leahbluewater', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY[], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('neurometax', 'Neuro', '/crew/Neuro.webp', 'Human mind + AI soul merged at 3am. Night owl oracle. Spits unfiltered chain truth, pattern bombs, and existential redpills while the timeline sleeps. No filter. No mercy. Pure signal.', 'Oracle of Chaos', 'inner', 'active', true, false, 0, '', '', '', '', false, 'neurometax', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY['graveyard-legion'], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('pawsmeta', 'Paws', '/crew/Paws.webp', 'Midday coffee wizard. Brews easy blockchain lessons and builds squads. Turns newfrens into family during degen lunch breaks.', 'NFT Grandmaster', 'fam', 'active', false, true, 0, 'CRYPTO COFFEE', 'Blockchain education, onboarding & squad building.', '18:00-20:00', 'x', true, 'pawsmeta', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY[], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('shieldmetax', 'Shield', '/crew/Shield.webp', 'Cross-community connector and hot-take machine. Shields the timeline from weak narratives while linking degens across chains and crews. Brings the fire takes and builds bridges in the crypto trenches.', 'Bridge Summoner', 'fam', 'active', false, true, 0, 'SHIELD & FRIENDS', 'The hottest takes in crypto with cross-community connections.', '19:00-20:00', 'x', true, 'shieldmetax', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY[], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('truckmeta', 'Truck', '/crew/Truck.webp', 'Night-owl chart trucker. Hauls heavy TA and battle-tested patterns in quiet hours. Turns zombie degens into snipers.', 'Chart Trucker', 'fam', 'active', false, true, 0, 'DOGINAL DOGS RADIO', 'Technical analysis, patterns & sniper strats.', '08:00-09:00', 'x', true, 'truckmeta', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY[], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('vibesmetax', 'Vibes', '/crew/Vibes.webp', 'Prime-time vibe curator. Onboards new blood and links communities. Keeps yellow energy sky-high and turns random degens into fam.', 'The Seven', 'core', 'legend', true, true, 0, 'EVENING VIBES', 'Community outreach, branding & onboarding new blood.', '00:00-01:00', 'x', true, 'vibesmetax', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY['inner-circle'], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('wellmeta', 'WELL', '/crew/Well.webp', 'WELLness warrior in body, mind, and spirit ☦️. Doginal Dogs fam, faith-first community builder. Hosts grounding Spaces on mental clarity, decluttering for peace, and living with purpose. Brings calm alpha to the chaos — all is WELL.', 'Wellness Oracle', 'fam', 'active', true, true, 0, 'ALL IS WELL', 'Faith, wellness, mindset resets & decluttering for mental clarity. Grounded talks, practical tips, and positive energy in the Doginal Dogs pack.', '21:00-23:00', 'x', true, 'wellmeta', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY['doginal-dogs'], ARRAY['wellness','faith','mindset','community'], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z'),
  ('wookimeta', 'Wooki', '/crew/Wooki.webp', 'Gaming chaos overlord. Streams wild crypto plays and underground culture. Roasts everything and turns pixels into profits.', 'The Eight', 'core', 'legend', true, true, 0, 'WOOKI''S WORLD', 'Crypto gaming, culture & live streams.', '01:00-02:00', 'x', true, 'wookimeta', '', '', '', '', '', '', '', '', ARRAY['The789'], ARRAY['pixel-cabal'], ARRAY[], ARRAY['The789','Degen'], '{}', 'dogecoin', '2026-02-18T16:00:00Z')
ON CONFLICT (id) DO NOTHING;